BEGIN;
--
-- Create model Dish
--
CREATE TABLE "core_dish" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL UNIQUE, "description" text NOT NULL, "video_url" varchar(512) NOT NULL, "time_to_cook_minutes" smallint NOT NULL CHECK ("time_to_cook_minutes" >= 0), "recipe_steps" text NOT NULL, "special_instructions" text NOT NULL, "required_utensils" varchar(255) NOT NULL);
--
-- Create model Ingredient
--
CREATE TABLE "core_ingredient" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL UNIQUE);
--
-- Create model ServiceArea
--
CREATE TABLE "core_servicearea" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "pincode" varchar(10) NOT NULL UNIQUE, "city" varchar(50) NOT NULL, "name" varchar(100) NOT NULL);
--
-- Create model Cook
--
CREATE TABLE "core_cook" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "full_name" varchar(100) NOT NULL, "phone_number" varchar(20) NOT NULL UNIQUE, "has_set_availability" boolean NOT NULL, "wallet_balance" numeric(10, 2) NOT NULL, "availability_last_updated" timestamp with time zone NULL, "years_of_experience" smallint NOT NULL CHECK ("years_of_experience" >= 0), "onboarding_quiz_score" smallint NOT NULL CHECK ("onboarding_quiz_score" >= 0), "cooking_test_score" smallint NOT NULL CHECK ("cooking_test_score" >= 0), "overall_competence_score" double precision NOT NULL, "kyc_status" varchar(20) NOT NULL, "kyc_document_url" varchar(512) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "user_id" integer NOT NULL UNIQUE);
CREATE TABLE "core_cook_certified_dishes" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cook_id" bigint NOT NULL, "dish_id" bigint NOT NULL);
CREATE TABLE "core_cook_service_areas" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cook_id" bigint NOT NULL, "servicearea_id" bigint NOT NULL);
--
-- Create model AvailabilitySlot
--
CREATE TABLE "core_availabilityslot" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "day_of_week" integer NOT NULL, "start_time" time NOT NULL, "end_time" time NOT NULL, "cook_id" bigint NOT NULL);
--
-- Create model DishIngredient
--
CREATE TABLE "core_dishingredient" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" numeric(7, 2) NOT NULL, "unit" varchar(5) NOT NULL, "is_must_have" boolean NOT NULL, "dish_id" bigint NOT NULL, "ingredient_id" bigint NOT NULL);
--
-- Add field ingredients to dish
--
-- (no-op)
--
-- Create model ScheduledTask
--
CREATE TABLE "core_scheduledtask" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "dish_name" varchar(150) NOT NULL, "date" date NOT NULL, "start_time" time NOT NULL, "cook_earnings" numeric(6, 2) NOT NULL, "status" varchar(20) NOT NULL, "cook_id" bigint NOT NULL);
CREATE INDEX "core_dish_name_72afa03c_like" ON "core_dish" ("name" varchar_pattern_ops);
CREATE INDEX "core_ingredient_name_5686f353_like" ON "core_ingredient" ("name" varchar_pattern_ops);
CREATE INDEX "core_servicearea_pincode_52458e26_like" ON "core_servicearea" ("pincode" varchar_pattern_ops);
ALTER TABLE "core_cook" ADD CONSTRAINT "core_cook_user_id_69b75b18_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_cook_phone_number_0d8c24bc_like" ON "core_cook" ("phone_number" varchar_pattern_ops);
ALTER TABLE "core_cook_certified_dishes" ADD CONSTRAINT "core_cook_certified_dishes_cook_id_dish_id_87fb9681_uniq" UNIQUE ("cook_id", "dish_id");
ALTER TABLE "core_cook_certified_dishes" ADD CONSTRAINT "core_cook_certified_dishes_cook_id_e28db048_fk_core_cook_id" FOREIGN KEY ("cook_id") REFERENCES "core_cook" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_cook_certified_dishes" ADD CONSTRAINT "core_cook_certified_dishes_dish_id_0e49304f_fk_core_dish_id" FOREIGN KEY ("dish_id") REFERENCES "core_dish" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_cook_certified_dishes_cook_id_e28db048" ON "core_cook_certified_dishes" ("cook_id");
CREATE INDEX "core_cook_certified_dishes_dish_id_0e49304f" ON "core_cook_certified_dishes" ("dish_id");
ALTER TABLE "core_cook_service_areas" ADD CONSTRAINT "core_cook_service_areas_cook_id_servicearea_id_debfba91_uniq" UNIQUE ("cook_id", "servicearea_id");
ALTER TABLE "core_cook_service_areas" ADD CONSTRAINT "core_cook_service_areas_cook_id_65430c97_fk_core_cook_id" FOREIGN KEY ("cook_id") REFERENCES "core_cook" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_cook_service_areas" ADD CONSTRAINT "core_cook_service_ar_servicearea_id_1bd5a66c_fk_core_serv" FOREIGN KEY ("servicearea_id") REFERENCES "core_servicearea" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_cook_service_areas_cook_id_65430c97" ON "core_cook_service_areas" ("cook_id");
CREATE INDEX "core_cook_service_areas_servicearea_id_1bd5a66c" ON "core_cook_service_areas" ("servicearea_id");
ALTER TABLE "core_availabilityslot" ADD CONSTRAINT "core_availabilityslot_cook_id_91cb933d_fk_core_cook_id" FOREIGN KEY ("cook_id") REFERENCES "core_cook" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_availabilityslot_cook_id_91cb933d" ON "core_availabilityslot" ("cook_id");
ALTER TABLE "core_dishingredient" ADD CONSTRAINT "core_dishingredient_dish_id_a8142e21_fk_core_dish_id" FOREIGN KEY ("dish_id") REFERENCES "core_dish" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_dishingredient" ADD CONSTRAINT "core_dishingredient_ingredient_id_32afe13b_fk_core_ingr" FOREIGN KEY ("ingredient_id") REFERENCES "core_ingredient" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_dishingredient_dish_id_a8142e21" ON "core_dishingredient" ("dish_id");
CREATE INDEX "core_dishingredient_ingredient_id_32afe13b" ON "core_dishingredient" ("ingredient_id");
ALTER TABLE "core_scheduledtask" ADD CONSTRAINT "core_scheduledtask_cook_id_56be9c59_fk_core_cook_id" FOREIGN KEY ("cook_id") REFERENCES "core_cook" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_scheduledtask_cook_id_56be9c59" ON "core_scheduledtask" ("cook_id");
COMMIT;
