# Generated by Django 5.2.4 on 2025-11-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='required_utensils',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='time_to_cook_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='dish',
            name='video_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
