# Generated by Django 5.2.4 on 2025-11-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dish_description_dish_recipe_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='availability_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cook',
            name='has_set_availability',
            field=models.BooleanField(default=False),
        ),
    ]
