# Generated by Django 5.2.4 on 2025-11-03 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cook_availability_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='cooking_test_score',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='kyc_document_url',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='onboarding_quiz_score',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='overall_competence_score',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='recipe_steps',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='required_utensils',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='special_instructions',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='time_to_cook_minutes',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='estimated_duration_minutes',
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='core.ingredient'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='cook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.cook'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20),
        ),
        migrations.DeleteModel(
            name='DishIngredient',
        ),
    ]
