# Generated by Django 5.2.4 on 2025-11-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cook_cooking_test_score_remove_cook_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='certified_dishes',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='service_areas',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='availability_last_updated',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='has_set_availability',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='years_of_experience',
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
        migrations.DeleteModel(
            name='ServiceArea',
        ),
    ]
