# Generated by Django 5.2.4 on 2025-11-03 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_dish_ingredients_remove_cook_certified_dishes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, max_length=512)),
                ('time_to_cook_minutes', models.PositiveSmallIntegerField(default=30)),
                ('recipe_steps', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('required_utensils', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='availability_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cook',
            name='cooking_test_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cook',
            name='has_set_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cook',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cook',
            name='kyc_document_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='cook',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='cook',
            name='onboarding_quiz_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cook',
            name='overall_competence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cook',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='core.cook')),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='certified_dishes',
            field=models.ManyToManyField(blank=True, to='core.dish'),
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('ml', 'Milliliters'), ('pcs', 'Pieces'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('unit', 'Unit')], max_length=5)),
                ('is_must_have', models.BooleanField(default=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='core.DishIngredient', to='core.ingredient'),
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('cook_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='core.cook')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish')),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='service_areas',
            field=models.ManyToManyField(blank=True, to='core.servicearea'),
        ),
    ]
